import { ThemeProvider } from "@/contexts/ThemeContext";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import { useContext } from "react";
import { HambuguerMenu } from "@/components/hambugerMenu";
import SwitchMode from "@/components/SwitchMode";
import { Header } from "@/components/Header";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <html lang="pt-br">
        <body className={` ${openSans.className}`}>
          <Header />
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
